# Generated by Django 2.2 on 2019-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.CharField(blank=True, max_length=5, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('editor', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_release', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('fileblob', models.FileField(blank=True, upload_to='')),
                ('file_content_type', models.CharField(max_length=500)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('id_registry', models.IntegerField(blank=True, null=True)),
                ('table', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
